package com.synapticloop.sample.h2zero.mysql.model.util;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//            (java-create-model-statistics.templar)

import com.synapticloop.sample.h2zero.mysql.model.User;
import com.synapticloop.sample.h2zero.mysql.model.Pet;
import com.synapticloop.sample.h2zero.mysql.model.UserPet;

import java.lang.StringBuilder;

public class Statistics {
	public static String getHitCountJson() {
		return("[" +
			User.getHitCountJson() +
			", " +
			Pet.getHitCountJson() +
			", " +
			UserPet.getHitCountJson() +
		"]");
	}
}