package com.synapticloop.sample.h2zero.mysql.taglib.user;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//          (java-create-taglib-finder-find-all.templar)

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.PageContext;
import jakarta.servlet.jsp.tagext.BodyTagSupport;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


import com.synapticloop.sample.h2zero.mysql.model.User;
import com.synapticloop.sample.h2zero.mysql.finder.UserFinder;
import com.synapticloop.sample.h2zero.mysql.model.util.Constants;

import com.synapticloop.h2zero.extension.taglib.BaseVarTag;

@SuppressWarnings("serial")
public class FindAllTag extends BaseVarTag {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.USER_BINDER;

	private static final Logger LOGGER = LoggerFactory.getLogger(FindAllTag.class);


	@Override
	public int doStartTag() throws JspException {
		if(limit == null) {
			pageContext.setAttribute(var, UserFinder.findAll().executeSilent());
		} else {
			pageContext.setAttribute(var, UserFinder.findAll().withLimit(limit).withOffset(offset).executeSilent());
		}
		return(EVAL_BODY_INCLUDE);
	}

}