package synapticloop.sample.h2zero.mysql.taglib.userTitle;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//           (java-create-taglib-finder.templar)

import javax.servlet.jsp.JspException;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


import synapticloop.sample.h2zero.mysql.model.util.Constants;
import synapticloop.sample.h2zero.mysql.finder.UserTitleFinder;
import com.synapticloop.h2zero.extension.taglib.BaseVarTag;


@SuppressWarnings("serial")
public class FindIdUserTitleNmUserTitleOrderedTag extends BaseVarTag {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.USER_TITLE_BINDER;
	private static final Logger LOGGER = LoggerFactory.getLogger(FindIdUserTitleNmUserTitleOrderedTag.class);


	@Override
	public int doStartTag() throws JspException {
		if(limit != null) {
			pageContext.setAttribute(var, UserTitleFinder.findIdUserTitleNmUserTitleOrderedSilent(limit, offset));
		} else {
			pageContext.setAttribute(var, UserTitleFinder.findIdUserTitleNmUserTitleOrderedSilent());
		}
		return(EVAL_BODY_INCLUDE);
	}

}