package synapticloop.sample.h2zero.mysql.model.util;

//        - - - - thoughtfully generated by synapticloop h2zero - - - -        
//          with the use of synapticloop templar templating language
//            (/java/model/java-create-model-statistics.templar)

import synapticloop.sample.h2zero.mysql.model.User;
import synapticloop.sample.h2zero.mysql.model.Pet;
import synapticloop.sample.h2zero.mysql.model.UserPet;

import java.lang.StringBuilder;

public class Statistics {
	public static String getHitCountJson() {
		return("[" +
			User.getHitCountJson() +
			", " +
			Pet.getHitCountJson() +
			", " +
			UserPet.getHitCountJson() +
		"]");
	}
}